### ISSUE TITLE
sudo: jackit: python errors

### ISSUE THREAD

**Issue by g33k247** [curiousmaster/JackItNG#1]
Any recommendations under Ubuntu 22.04 and python3?

```
┌──(linuxgeek㉿SPEEDY)-[~/git/JackItNG]
└─$ sudo /home/linuxgeek/.local/bin/jackit

/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/home/linuxgeek/.local/bin/jackit", line 4, in <module>
    __import__('pkg_resources').require('JackItNG==0.1.0')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'JackItNG==0.1.0' distribution was not found and is required by the application

```

**Comment by curiousmaster** [comment]
Will have a look at it tomorrow..

**Comment by curiousmaster** [comment]
Should now work on a fresh Ubuntu 22.04 running Python 3 with latest updates installed.
